language: python
python:

  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
    global:
       - CONDA_INSTALL_LOCN="${HOME}/conda"

install:
    - mkdir -p ${HOME}/cache/pkgs
    - source activate ${CONDA_INSTALL_LOCN}
    - conda install --yes --file requirements.txt

script:
  - pytest # or py.test for Python versions 3.5 and below